# Generated by Django 4.0.5 on 2022-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('birthday_year', models.PositiveIntegerField()),
                ('email', models.CharField(default=False, max_length=50, unique=True)),
            ],
        ),
    ]
